./lua/test.sh ./lua/date.lua
./lua/test.sh ./lua/file_io.lua
./lua/test.sh ./lua/max_min.lua
./lua/test.sh ./lua/random.lua
./lua/test.sh ./lua/remove.lua
./lua/test.sh ./lua/round_num.lua
./lua/test.sh ./lua/sin30.lua
./lua/test.sh ./lua/sort.lua
./lua/test.sh ./lua/strings.lua
